services:
  db:
    build:
      dockerfile_inline: |
        FROM postgres:15.8
        RUN apt update -y && apt upgrade -y
        RUN apt install curl -y
        COPY ./.docker/postgres/custom-entrypoint.sh /usr/local/bin/custom-entrypoint.sh
        ENTRYPOINT ["/usr/local/bin/custom-entrypoint.sh"]
        CMD ["postgres"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./.docker/postgres/init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql

  s3:
    build:
      dockerfile_inline: |
        FROM localstack/localstack:4.2
        RUN apt update -y && apt upgrade -y
    environment:
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    ports:
      - ${AWS_PORT:-4566}:4566
    volumes:
      - ./.docker/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
