version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    golines:
      max-len: 100
      shorten-comments: true
