services:
  db:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  s3:
    image: localstack/localstack:4.5.0
    environment:
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    ports:
      - ${AWS_PORT:-4566}:4566
