//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "catedras")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub codigo: Uuid,
    #[sea_orm(column_type = "Text")]
    pub nombre: String,
    pub codigo_materia: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::docentes::Entity")]
    Docentes,
    #[sea_orm(
        belongs_to = "super::materias::Entity",
        from = "Column::CodigoMateria",
        to = "super::materias::Column::Codigo",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Materias,
}

impl Related<super::docentes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Docentes.def()
    }
}

impl Related<super::materias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Materias.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
