//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comentarios")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub codigo: i32,
    #[sea_orm(column_type = "Text")]
    pub cuatrimestre: String,
    #[sea_orm(column_type = "Text")]
    pub contenido: String,
    pub codigo_docente: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::docentes::Entity",
        from = "Column::CodigoDocente",
        to = "super::docentes::Column::Codigo",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Docentes,
}

impl Related<super::docentes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Docentes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
