//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "docentes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub codigo: Uuid,
    #[sea_orm(column_type = "Text")]
    pub nombre: String,
    pub respuestas: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub acepta_critica: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub asistencia: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub buen_trato: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub claridad: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub clase_organizada: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cumple_horarios: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fomenta_participacion: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub panorama_amplio: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub responde_mails: Option<f64>,
    pub codigo_catedra: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::catedras::Entity",
        from = "Column::CodigoCatedra",
        to = "super::catedras::Column::Codigo",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Catedras,
    #[sea_orm(has_many = "super::comentarios::Entity")]
    Comentarios,
}

impl Related<super::catedras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Catedras.def()
    }
}

impl Related<super::comentarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comentarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
