//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "materias")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub codigo: i32,
    #[sea_orm(column_type = "Text")]
    pub nombre: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::catedras::Entity")]
    Catedras,
}

impl Related<super::catedras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Catedras.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
