//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::catedras::Entity as Catedras;
pub use super::comentarios::Entity as Comentarios;
pub use super::docentes::Entity as Docentes;
pub use super::materias::Entity as Materias;
